#!/usr/bin/env bash
# Utility script to invoke front-end style checks in the front directory, or other
# tools in the repository using pnpm
# Usage: ./invoke_pnpm lint|format|graphql-types FILE [FILE...]

mode=$1
shift

declare -a front_files statviz_files shared_components_files

# strip prefix from all given filepaths and add to file_collections
for file in "$@"; do
    if [[ $file == front/* ]]; then
        file_collections["front"]+=("${file#front/}")
    elif [[ $file == statviz/* ]]; then
        file_collections["statviz"]+=("${file#statviz/}")
    elif [[ $file == shared-components/* ]]; then
        shared_components_files+=("${file#shared-components/}")
    fi
done

# TODO: move this to the pre-commit config. Otherwise people need to install pnpm
if [[ "$mode" = "lint" ]]; then
    pnpm lint:fix "$@"
elif [[ "$mode" = "format" ]]; then
    pnpm format:write "$@"
elif [[ "$mode" = "tsc" ]]; then
    echo "${file_collections["shared-components"]}"
    pnpm --cwd front run tsc:precommit --noEmit "${file_collections["front"]}"
    pnpm --cwd statviz run tsc:precommit --noEmit "${file_collections["statviz"]}"
    pnpm --cwd shared-components run tsc:precommit --noEmit "${shared_components_files[@]}"
elif [[ "$mode" = "graphql-types" ]]; then
    pnpm --cwd front run generate-graphql-ts-types && pnpm --cwd statviz run generate-graphql-ts-types
else
    echo "Unknown mode: $mode" >&2
    exit 1
fi
