const movedBoxesFacts = [
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-04-02",
    targetId: "Gelöschte Boxen",
    categoryId: 3,
    boxesCount: 1,
    itemsCount: 78,
    gender: "Women",
    productName: "longsleeves",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-04-02",
    targetId: "Gelöschte Boxen",
    categoryId: 5,
    boxesCount: 1,
    itemsCount: 15,
    gender: "Women",
    productName: "summer shoes",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-06-05",
    targetId: "Packstation",
    categoryId: 5,
    boxesCount: -1,
    itemsCount: -10,
    gender: "UnisexAdult",
    productName: "rubber boots",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 3,
    boxesCount: 1,
    itemsCount: 15,
    gender: "Women",
    productName: "summer jackets",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 3,
    boxesCount: 2,
    itemsCount: 34,
    gender: "Women",
    productName: "summer jackets",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 3,
    boxesCount: 1,
    itemsCount: 80,
    gender: "Women",
    productName: "t-shirts",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 3,
    boxesCount: 1,
    itemsCount: 57,
    gender: "Women",
    productName: "t-shirts",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 3,
    boxesCount: 3,
    itemsCount: 221,
    gender: "Women",
    productName: "t-shirts",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 3,
    boxesCount: 1,
    itemsCount: 11,
    gender: "Women",
    productName: "winter jackets",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 5,
    boxesCount: 2,
    itemsCount: 19,
    gender: "UnisexAdult",
    productName: "rubber boots",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 5,
    boxesCount: 2,
    itemsCount: 35,
    gender: "UnisexKid",
    productName: "rubber boots",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 5,
    boxesCount: 1,
    itemsCount: 26,
    gender: "Women",
    productName: "summer shoes",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 5,
    boxesCount: 1,
    itemsCount: 25,
    gender: "Women",
    productName: "summer shoes",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 5,
    boxesCount: 6,
    itemsCount: 129,
    gender: "UnisexKid",
    productName: "summer shoes",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 5,
    boxesCount: 1,
    itemsCount: 29,
    gender: "UnisexBaby",
    productName: "summer shoes",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 9,
    boxesCount: 1,
    itemsCount: 17,
    gender: "none",
    productName: "bed sheets",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 12,
    boxesCount: 2,
    itemsCount: 89,
    gender: "Women",
    productName: "gloves",
    tagIds: [],
  },
  {
    __typename: "MovedBoxesResult",
    movedOn: "2023-07-02",
    targetId: "Shipment1Calai",
    categoryId: 12,
    boxesCount: 1,
    itemsCount: 59,
    gender: "UnisexKid",
    productName: "summer hats",
    tagIds: [],
  },
];

const categories = [
  {
    __typename: "DimensionInfo",
    id: 1,
    name: "Underwear / Nightwear",
  },
  {
    __typename: "DimensionInfo",
    id: 2,
    name: "Bottoms",
  },
  {
    __typename: "DimensionInfo",
    id: 3,
    name: "Tops",
  },
  {
    __typename: "DimensionInfo",
    id: 4,
    name: "Accessories",
  },
  {
    __typename: "DimensionInfo",
    id: 5,
    name: "Jackets / Outerwear",
  },
  {
    __typename: "DimensionInfo",
    id: 7,
    name: "Skirts / Dresses",
  },
  {
    __typename: "DimensionInfo",
    id: 8,
    name: "Baby",
  },
  {
    __typename: "DimensionInfo",
    id: 9,
    name: "Other",
  },
  {
    __typename: "DimensionInfo",
    id: 10,
    name: "Hygiene",
  },
  {
    __typename: "DimensionInfo",
    id: 11,
    name: "Food & Kitchen",
  },
  {
    __typename: "DimensionInfo",
    id: 12,
    name: "Clothing",
  },
  {
    __typename: "DimensionInfo",
    id: 13,
    name: "Equipment",
  },
  {
    __typename: "DimensionInfo",
    id: 14,
    name: "Toys & Games",
  },
  {
    __typename: "DimensionInfo",
    id: 15,
    name: "Medication",
  },
  {
    __typename: "DimensionInfo",
    id: 18,
    name: "Books & Stationery",
  },
  {
    __typename: "DimensionInfo",
    id: 19,
    name: "Water",
  },
  {
    __typename: "DimensionInfo",
    id: 20,
    name: "Shelter",
  },
];

const targets = [
  {
    __typename: "TargetDimensionInfo",
    id: "Shipment1Calai",
    name: "Shipment1Calai",
    type: "OutgoingLocation",
  },
  {
    __typename: "TargetDimensionInfo",
    id: "V93 LR",
    name: "V93 LR",
    type: "OutgoingLocation",
  },
  {
    __typename: "TargetDimensionInfo",
    id: "Gelöschte Boxen",
    name: "Gelöschte Boxen",
    type: "OutgoingLocation",
  },
  {
    __typename: "TargetDimensionInfo",
    id: "Lost",
    name: "Lost",
    type: "BoxState",
  },
  {
    __typename: "TargetDimensionInfo",
    id: "Scrap",
    name: "Scrap",
    type: "BoxState",
  },
];

export const movedBoxesResultMockData = {
  movedBoxes: {
    __typename: "MovedBoxesData",
    facts: movedBoxesFacts,
    dimensions: {
      __typename: "MovedBoxDataDimensions",
      target: targets,
      category: categories,
    },
  },
};
