runtime: python310
service: v2-staging
entrypoint: gunicorn -b :$PORT
handlers:
- url: /graphql
  script: auto
  secure: always
- url: /
  secure: always
  static_files: react-build/index.html
  upload: react-build/index.html
- url: /static/(.*)
  secure: always
  static_files: react-build/static/\1
  upload: react-build/static/(.*)
- url: /(.*)
  secure: always
  static_files: react-build/index.html
  upload: react-build/index.html
