runtime: python312
service: v2-staging
entrypoint: gunicorn -b :$PORT boxtribute_server.main:app
automatic_scaling:
  max_instances: 5
handlers:
  - url: /graphql
    script: auto
    secure: always
  - url: /auth0-slack-bridge
    script: auto
    secure: always
  - url: /cron/(.*)
    script: auto
    secure: always
  - url: /
    secure: always
    static_files: front-build/index.html
    upload: front-build/index.html
  - url: /manifest.json
    static_files: front-build/manifest.json
    upload: front-build/manifest.json
  - url: /heapanalytics.js
    static_files: front-build/heapanalytics.js
    upload: front-build/heapanalytics.js
  - url: /assets/(.*)
    secure: always
    static_files: front-build/assets/\1
    upload: front-build/assets/(.*)
  - url: /(.*\.(ico|png|svg|woff2))$
    secure: always
    static_files: front-build/\1
    upload: front-build/(.*\.(ico|png|svg|woff2))$
  - url: /(.*)
    secure: always
    static_files: front-build/index.html
    upload: front-build/index.html
