export const boxesTableDataMock = [
  {
    productName: "Leggings",
    id: "95",
    labelIdentifier: "930956",
    gender: "Boy",
    items: 27,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "baby towels",
    id: "105",
    labelIdentifier: "264393",
    gender: "UnisexBaby",
    items: 75,
    size: "52",
    state: "MarkedForShipment",
    location: "LOST",
  },
  {
    productName: "Duvet",
    id: "132",
    labelIdentifier: "322526",
    gender: "none",
    items: 96,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Shampoo",
    id: "143",
    labelIdentifier: "695326",
    gender: "none",
    items: 72,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Onesie thick",
    id: "145",
    labelIdentifier: "824368",
    gender: "UnisexBaby",
    items: 27,
    size: "121",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "WD BLANKETS",
    id: "151",
    labelIdentifier: "619255",
    gender: "none",
    items: 91,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Shoes",
    id: "164",
    labelIdentifier: "749073",
    gender: "UnisexKid",
    items: 43,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Socks",
    id: "166",
    labelIdentifier: "161451",
    gender: "UnisexKid",
    items: 50,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Shortsleeve",
    id: "196",
    labelIdentifier: "146657",
    gender: "Women",
    items: 56,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Summer hats",
    id: "206",
    labelIdentifier: "511544",
    gender: "UnisexBaby",
    items: 96,
    size: "119",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Soap",
    id: "213",
    labelIdentifier: "281699",
    gender: "none",
    items: 100,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Trousers ",
    id: "215",
    labelIdentifier: "512516",
    gender: "UnisexKid",
    items: 67,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Summer hats",
    id: "218",
    labelIdentifier: "119373",
    gender: "Boy",
    items: 41,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Flour (1kg)",
    id: "242",
    labelIdentifier: "848787",
    gender: "none",
    items: 7,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Soap",
    id: "268",
    labelIdentifier: "792558",
    gender: "none",
    items: 77,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Underwear",
    id: "288",
    labelIdentifier: "810354",
    gender: "Men",
    items: 74,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Winter hats",
    id: "298",
    labelIdentifier: "173094",
    gender: "Men",
    items: 54,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Tights",
    id: "309",
    labelIdentifier: "189496",
    gender: "UnisexKid",
    items: 6,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Washing powder",
    id: "316",
    labelIdentifier: "178058",
    gender: "none",
    items: 92,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "baby scarves",
    id: "318",
    labelIdentifier: "850888",
    gender: "UnisexBaby",
    items: 86,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Sanitary pads",
    id: "319",
    labelIdentifier: "562650",
    gender: "none",
    items: 12,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Jumper",
    id: "324",
    labelIdentifier: "624148",
    gender: "Women",
    items: 57,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Beans (400g)",
    id: "343",
    labelIdentifier: "497877",
    gender: "none",
    items: 40,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "baby gloves",
    id: "371",
    labelIdentifier: "942820",
    gender: "UnisexBaby",
    items: 91,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Razors",
    id: "380",
    labelIdentifier: "790817",
    gender: "none",
    items: 95,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Duvet",
    id: "381",
    labelIdentifier: "362446",
    gender: "none",
    items: 97,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "baby socks",
    id: "386",
    labelIdentifier: "530171",
    gender: "UnisexBaby",
    items: 84,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Adult diapers",
    id: "387",
    labelIdentifier: "553355",
    gender: "UnisexAdult",
    items: 94,
    size: "115",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Longsleeve",
    id: "395",
    labelIdentifier: "210015",
    gender: "Boy",
    items: 44,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Onesie thin",
    id: "406",
    labelIdentifier: "494945",
    gender: "UnisexBaby",
    items: 35,
    size: "123",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Jacket Thick",
    id: "419",
    labelIdentifier: "762258",
    gender: "Men",
    items: 69,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Jumper Thin",
    id: "455",
    labelIdentifier: "223807",
    gender: "Girl",
    items: 37,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "WD BABY CLOTHES",
    id: "457",
    labelIdentifier: "998797",
    gender: "none",
    items: 82,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Jumper Thick",
    id: "470",
    labelIdentifier: "980742",
    gender: "Girl",
    items: 33,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Leggings",
    id: "471",
    labelIdentifier: "151120",
    gender: "Boy",
    items: 48,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Diapers Size 5",
    id: "474",
    labelIdentifier: "142618",
    gender: "none",
    items: 18,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Socks",
    id: "476",
    labelIdentifier: "553928",
    gender: "Women",
    items: 87,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Washing powder",
    id: "488",
    labelIdentifier: "454330",
    gender: "none",
    items: 85,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Flour (1kg)",
    id: "489",
    labelIdentifier: "763294",
    gender: "none",
    items: 92,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Baby Onesie ",
    id: "494",
    labelIdentifier: "744347",
    gender: "UnisexBaby",
    items: 46,
    size: "52",
    state: "MarkedForShipment",
    location: "LOST",
  },
  {
    productName: "Diapers Size 5",
    id: "497",
    labelIdentifier: "291758",
    gender: "none",
    items: 74,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Blanket",
    id: "523",
    labelIdentifier: "218908",
    gender: "none",
    items: 49,
    size: "68",
    state: "MarkedForShipment",
    location: "LOST",
  },
  {
    productName: "Bags",
    id: "539",
    labelIdentifier: "700825",
    gender: "none",
    items: 13,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "WD GLOVES",
    id: "575",
    labelIdentifier: "790388",
    gender: "none",
    items: 33,
    size: "68",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "WD JACKET",
    id: "581",
    labelIdentifier: "747257",
    gender: "none",
    items: 84,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "baby towels",
    id: "599",
    labelIdentifier: "814449",
    gender: "UnisexBaby",
    items: 76,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Socks",
    id: "604",
    labelIdentifier: "908444",
    gender: "Girl",
    items: 57,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Jacket Thin",
    id: "649",
    labelIdentifier: "924582",
    gender: "Boy",
    items: 27,
    size: "52",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Bottom",
    id: "668",
    labelIdentifier: "186654",
    gender: "UnisexBaby",
    items: 47,
    size: "121",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Summer hats",
    id: "701",
    labelIdentifier: "444866",
    gender: "UnisexBaby",
    items: 29,
    size: "123",
    state: "Lost",
    location: "LOST",
  },
  {
    productName: "Socks",
    id: "2",
    labelIdentifier: "703346",
    gender: "Women",
    items: 32,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Sweatpants",
    id: "6",
    labelIdentifier: "908238",
    gender: "Boy",
    items: 84,
    size: "52",
    state: "MarkedForShipment",
    location: "SCRAP",
  },
  {
    productName: "Pasta (500g)",
    id: "23",
    labelIdentifier: "304023",
    gender: "none",
    items: 90,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Baby carrier",
    id: "25",
    labelIdentifier: "137560",
    gender: "UnisexBaby",
    items: 28,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Snowsuit",
    id: "26",
    labelIdentifier: "841518",
    gender: "Boy",
    items: 70,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Shampoo",
    id: "45",
    labelIdentifier: "414391",
    gender: "none",
    items: 61,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Diapers Size 3",
    id: "56",
    labelIdentifier: "661120",
    gender: "none",
    items: 4,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Tarps",
    id: "78",
    labelIdentifier: "762791",
    gender: "none",
    items: 47,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Folding Beds",
    id: "82",
    labelIdentifier: "604360",
    gender: "none",
    items: 90,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Jumper Thick",
    id: "88",
    labelIdentifier: "494670",
    gender: "Girl",
    items: 67,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Pasta (500g)",
    id: "92",
    labelIdentifier: "413142",
    gender: "none",
    items: 64,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "WD JACKET",
    id: "103",
    labelIdentifier: "886780",
    gender: "none",
    items: 47,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Trousers",
    id: "139",
    labelIdentifier: "998332",
    gender: "Women",
    items: 45,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Toothpaste",
    id: "221",
    labelIdentifier: "679276",
    gender: "none",
    items: 4,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Sleeping Mats (UNHCR)",
    id: "228",
    labelIdentifier: "525446",
    gender: "none",
    items: 10,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Blanket",
    id: "246",
    labelIdentifier: "934710",
    gender: "none",
    items: 33,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Snow trousers",
    id: "261",
    labelIdentifier: "848089",
    gender: "Women",
    items: 1,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Rice (1kg)",
    id: "270",
    labelIdentifier: "206858",
    gender: "none",
    items: 40,
    size: "68",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Pyjamas",
    id: "282",
    labelIdentifier: "226946",
    gender: "Boy",
    items: 68,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
  {
    productName: "Top",
    id: "287",
    labelIdentifier: "993787",
    gender: "UnisexBaby",
    items: 17,
    size: "52",
    state: "Scrap",
    location: "SCRAP",
  },
];
