import { BoxRow } from "../types";

export const boxesTableDataMock: BoxRow[] = [
  {
    productName: "Leggings",
    labelIdentifier: "930956",
    gender: "Boy",
    items: 27,
    size: "52",
    state: "Lost",
  },
  {
    productName: "baby towels",
    labelIdentifier: "264393",
    gender: "UnisexBaby",
    items: 75,
    size: "52",
    state: "MarkedForShipment",
  },
  {
    productName: "Duvet",
    labelIdentifier: "322526",
    gender: "none",
    items: 96,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Shampoo",
    labelIdentifier: "695326",
    gender: "none",
    items: 72,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Onesie thick",
    labelIdentifier: "824368",
    gender: "UnisexBaby",
    items: 27,
    size: "121",
    state: "Lost",
  },
  {
    productName: "WD BLANKETS",
    labelIdentifier: "619255",
    gender: "none",
    items: 91,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Shoes",
    labelIdentifier: "749073",
    gender: "UnisexKid",
    items: 43,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Socks",
    labelIdentifier: "161451",
    gender: "UnisexKid",
    items: 50,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Shortsleeve",
    labelIdentifier: "146657",
    gender: "Women",
    items: 56,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Summer hats",
    labelIdentifier: "511544",
    gender: "UnisexBaby",
    items: 96,
    size: "119",
    state: "Lost",
  },
  {
    productName: "Soap",
    labelIdentifier: "281699",
    gender: "none",
    items: 100,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Trousers ",
    labelIdentifier: "512516",
    gender: "UnisexKid",
    items: 67,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Summer hats",
    labelIdentifier: "119373",
    gender: "Boy",
    items: 41,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Flour (1kg)",
    labelIdentifier: "848787",
    gender: "none",
    items: 7,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Soap",
    labelIdentifier: "792558",
    gender: "none",
    items: 77,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Underwear",
    labelIdentifier: "810354",
    gender: "Men",
    items: 74,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Winter hats",
    labelIdentifier: "173094",
    gender: "Men",
    items: 54,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Tights",
    labelIdentifier: "189496",
    gender: "UnisexKid",
    items: 6,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Washing powder",
    labelIdentifier: "178058",
    gender: "none",
    items: 92,
    size: "68",
    state: "Lost",
  },
  {
    productName: "baby scarves",
    labelIdentifier: "850888",
    gender: "UnisexBaby",
    items: 86,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Sanitary pads",
    labelIdentifier: "562650",
    gender: "none",
    items: 12,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Jumper",
    labelIdentifier: "624148",
    gender: "Women",
    items: 57,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Beans (400g)",
    labelIdentifier: "497877",
    gender: "none",
    items: 40,
    size: "68",
    state: "Lost",
  },
  {
    productName: "baby gloves",
    labelIdentifier: "942820",
    gender: "UnisexBaby",
    items: 91,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Razors",
    labelIdentifier: "790817",
    gender: "none",
    items: 95,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Duvet",
    labelIdentifier: "362446",
    gender: "none",
    items: 97,
    size: "68",
    state: "Lost",
  },
  {
    productName: "baby socks",
    labelIdentifier: "530171",
    gender: "UnisexBaby",
    items: 84,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Adult diapers",
    labelIdentifier: "553355",
    gender: "UnisexAdult",
    items: 94,
    size: "115",
    state: "Lost",
  },
  {
    productName: "Longsleeve",
    labelIdentifier: "210015",
    gender: "Boy",
    items: 44,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Onesie thin",
    labelIdentifier: "494945",
    gender: "UnisexBaby",
    items: 35,
    size: "123",
    state: "Lost",
  },
  {
    productName: "Jacket Thick",
    labelIdentifier: "762258",
    gender: "Men",
    items: 69,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Jumper Thin",
    labelIdentifier: "223807",
    gender: "Girl",
    items: 37,
    size: "52",
    state: "Lost",
  },
  {
    productName: "WD BABY CLOTHES",
    labelIdentifier: "998797",
    gender: "none",
    items: 82,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Jumper Thick",
    labelIdentifier: "980742",
    gender: "Girl",
    items: 33,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Leggings",
    labelIdentifier: "151120",
    gender: "Boy",
    items: 48,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Diapers Size 5",
    labelIdentifier: "142618",
    gender: "none",
    items: 18,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Socks",
    labelIdentifier: "553928",
    gender: "Women",
    items: 87,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Washing powder",
    labelIdentifier: "454330",
    gender: "none",
    items: 85,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Flour (1kg)",
    labelIdentifier: "763294",
    gender: "none",
    items: 92,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Baby Onesie ",
    labelIdentifier: "744347",
    gender: "UnisexBaby",
    items: 46,
    size: "52",
    state: "MarkedForShipment",
  },
  {
    productName: "Diapers Size 5",
    labelIdentifier: "291758",
    gender: "none",
    items: 74,
    size: "68",
    state: "Lost",
  },
  {
    productName: "Blanket",
    labelIdentifier: "218908",
    gender: "none",
    items: 49,
    size: "68",
    state: "MarkedForShipment",
  },
  {
    productName: "Bags",
    labelIdentifier: "700825",
    gender: "none",
    items: 13,
    size: "52",
    state: "Lost",
  },
  {
    productName: "WD GLOVES",
    labelIdentifier: "790388",
    gender: "none",
    items: 33,
    size: "68",
    state: "Lost",
  },
  {
    productName: "WD JACKET",
    labelIdentifier: "747257",
    gender: "none",
    items: 84,
    size: "52",
    state: "Lost",
  },
  {
    productName: "baby towels",
    labelIdentifier: "814449",
    gender: "UnisexBaby",
    items: 76,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Socks",
    labelIdentifier: "908444",
    gender: "Girl",
    items: 57,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Jacket Thin",
    labelIdentifier: "924582",
    gender: "Boy",
    items: 27,
    size: "52",
    state: "Lost",
  },
  {
    productName: "Bottom",
    labelIdentifier: "186654",
    gender: "UnisexBaby",
    items: 47,
    size: "121",
    state: "Lost",
  },
  {
    productName: "Summer hats",
    labelIdentifier: "444866",
    gender: "UnisexBaby",
    items: 29,
    size: "123",
    state: "Lost",
  },
  {
    productName: "Socks",
    labelIdentifier: "703346",
    gender: "Women",
    items: 32,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Sweatpants",
    labelIdentifier: "908238",
    gender: "Boy",
    items: 84,
    size: "52",
    state: "MarkedForShipment",
  },
  {
    productName: "Pasta (500g)",
    labelIdentifier: "304023",
    gender: "none",
    items: 90,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Baby carrier",
    labelIdentifier: "137560",
    gender: "UnisexBaby",
    items: 28,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Snowsuit",
    labelIdentifier: "841518",
    gender: "Boy",
    items: 70,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Shampoo",
    labelIdentifier: "414391",
    gender: "none",
    items: 61,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Diapers Size 3",
    labelIdentifier: "661120",
    gender: "none",
    items: 4,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Tarps",
    labelIdentifier: "762791",
    gender: "none",
    items: 47,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Folding Beds",
    labelIdentifier: "604360",
    gender: "none",
    items: 90,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Jumper Thick",
    labelIdentifier: "494670",
    gender: "Girl",
    items: 67,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Pasta (500g)",
    labelIdentifier: "413142",
    gender: "none",
    items: 64,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "WD JACKET",
    labelIdentifier: "886780",
    gender: "none",
    items: 47,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Trousers",
    labelIdentifier: "998332",
    gender: "Women",
    items: 45,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Toothpaste",
    labelIdentifier: "679276",
    gender: "none",
    items: 4,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Sleeping Mats (UNHCR)",
    labelIdentifier: "525446",
    gender: "none",
    items: 10,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Blanket",
    labelIdentifier: "934710",
    gender: "none",
    items: 33,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Snow trousers",
    labelIdentifier: "848089",
    gender: "Women",
    items: 1,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Rice (1kg)",
    labelIdentifier: "206858",
    gender: "none",
    items: 40,
    size: "68",
    state: "Scrap",
  },
  {
    productName: "Pyjamas",
    labelIdentifier: "226946",
    gender: "Boy",
    items: 68,
    size: "52",
    state: "Scrap",
  },
  {
    productName: "Top",
    labelIdentifier: "993787",
    gender: "UnisexBaby",
    items: 17,
    size: "52",
    state: "Scrap",
  },
];
